# Generated by Django 2.2.3 on 2021-01-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image_path', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
