# Generated by Django 2.2.3 on 2021-01-29 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20210127_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='app',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='des',
            field=models.TextField(default='这东西已经不知道该怎么描述了'),
        ),
        migrations.AddField(
            model_name='image',
            name='key',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='image',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(default='不说了，看图'),
        ),
    ]
