# Generated by Django 2.2.3 on 2021-01-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20210129_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='key',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(),
        ),
    ]
