# Generated by Django 2.2.3 on 2021-01-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20210129_0812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Goods',
        ),
    ]
