# Generated by Django 2.2.3 on 2021-01-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20210129_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='exposure',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goods',
            name='tap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image_path',
            field=models.ImageField(upload_to='images'),
        ),
    ]
