# Generated by Django 2.2.3 on 2021-01-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20210131_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
