# Generated by Django 2.2.3 on 2021-01-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=32, unique=True)),
                ('nickname', models.TextField(max_length=256, null=True)),
                ('avatarurl', models.TextField(max_length=256, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('country', models.TextField(max_length=256, null=True)),
                ('province', models.TextField(max_length=256, null=True)),
                ('city', models.TextField(max_length=256, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
